openapi: 3.0.2
info:
  license:
    name: Apache-2.0
  title: PIACERE Model Checker
  version: "2.2.0"
paths:
  /modelcheck:
    post:
      summary: Verify a DOML model
      description: Send a DOML model in XMI format and a requirement to check.
        The response says whether the requirements are satisfied by the model,
        with a description of the issue if it is not.
      operationId: mc_openapi.handlers.post
      requestBody:
        content:
          application/xml:
            schema:
              type: string
        required: true
      parameters:
        - in: query
          name: version
          schema:
            type: string
          description: >
            The DOML version you're currently using, written as e.g. `2.0` or `V2_0`.
            If not specified, it will try to infer it by trying to parse it for each supported
            DOML version, starting with the most recent.
          required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - sat
                      - unsat
                      - dontknow
                  description:
                    type: string
                required:
                  - result
          description: OK - model checking succeded
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: malformed request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: internal error
components:
  schemas:
    error:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        message:
          type: string
          description: Error message for the user
        debug_message:
          type: string
          description: Detailed error message for debugging purposes
      required:
        - timestamp
        - message
